" Turn on line numbers
set number

" Turns off tab bar
set showtabline=0

" GUI Option to remove the Toolbar (T)
set guioptions-=T

" Sets the font and size
set guifont=Monaco:h14

" Maximize the window
set lines=999 columns=9999
